# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gonzalo Toledano
tagline:          'Personal Blog'
description:      'Android Developer'
url:              http://gnzlt.github.io
baseurl:          /

author:
  name:           'Gonzalo Toledano'
  twitter:            https://twitter.com/gnzlt

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gnzlt
